### ISSUE TITLE
Allow restricted control characters in request HeaderValues

### ISSUE THREAD

**Issue by deniaa** [vostok/clusterclient.transport.webrequest#1]
```
var chars = Enumerable.Range(15, 25).Select(x => (char) x).ToArray();
var s = new string(chars);
```

If we put this (in example) header value in `Headers` collection, exception from `WebHeaderCollection.Set` will be thrown:
```
Transport implementation threw an exception.
System.ArgumentException: Specified value has invalid Control characters.
Parameter name: value
   at System.Net.WebHeaderCollection.CheckBadChars(String name, Boolean isHeaderValue)
   at System.Net.WebHeaderCollection.Set(String name, String value)
   at Kontur.Clusterclient.Transport.Webrequest.WebRequestHeadersFiller.AssignHeadersDirectly(Headers headers, HttpWebRequest webRequest) in 
```

**Comment by iloktionov** [comment]
No longer relevant with migration to .NET Core. Closing.
